version: '3'
services:

  db:
    image: "mysql"
    # 5.7内存占用小，如果要性能更高可以使用mysql最新版
    container_name: mysql
    ports:
      - "3306:3306"
    command:
      [
        '--character-set-server=utf8mb4', #设置utf8编码
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Ix,eMsoxoag, # 数据库root密码
      MYSQL_DATABASE: movie # 初始化的数据库名

  movie:
    depends_on:
      - db
    image: "movie"
    container_name: movie
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:64.176.51.101"
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: db:3306 # mysql地址
      MYSQL_USER: root # mysql用户名
      MYSQL_PASSWORD: Ix,eMsoxoag, # mysql密码
      DATABASE_NAME: movie # mysql数据库
      LISTEN_ADDR: :8000 # 主程序监听地址，与ports后面端口保持一致

  # 瞭望塔 容器监听更新
  watchtower:
    image: containrrr/watchtower
    container_name: watcher
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: movie movie_watcher --cleanup --schedule "0 0 1 * * *"
    # command: movie movie_watcher --cleanup --interval 60
volumes:
  mysql_data:
