version: '3'
services:
  movie:
    depends_on:
      - db
    image: "movie"
    container_name: movie
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:64.176.51.101"
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: db:3306 # mysql地址
      MYSQL_USER: movie # mysql用户名
      MYSQL_PASSWORD: LwF7iFMNeXzC4p4z # mysql密码
      DATABASE_NAME: movie # mysql数据库
      LISTEN_ADDR: :8000 # 主程序监听地址，与ports后面端口保持一致

  # 瞭望塔 容器监听更新
  watchtower:
    image: containrrr/watchtower
    container_name: watcher
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: movie movie_watcher --cleanup --schedule "0 0 1 * * *"
    # command: movie movie_watcher --cleanup --interval 60
volumes:
  mysql_data:
